data = [
    {
        "ClientID": 1,
        "FirstName": "Alice",
        "LastName": "Smith",
        "Email": "alice.smith@example.com",
        "PhoneNumber": "+1234567890",
        "Address": "123 Maple Street",
        "City": "New York",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:10:00",
        "CompanyID": 1
    },
    {
        "ClientID": 2,
        "FirstName": "Bob",
        "LastName": "Johnson",
        "Email": "bob.johnson@example.com",
        "PhoneNumber": "+1987654321",
        "Address": "456 Oak Avenue",
        "City": "Los Angeles",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:15:00",
        "CompanyID": 1
    },
    {
        "ClientID": 3,
        "FirstName": "Carol",
        "LastName": "Williams",
        "Email": "carol.williams@example.com",
        "PhoneNumber": "+1478523690",
        "Address": "789 Pine Road",
        "City": "Chicago",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:20:00",
        "CompanyID": 1
    },
    {
        "ClientID": 4,
        "FirstName": "David",
        "LastName": "Brown",
        "Email": "david.brown@example.com",
        "PhoneNumber": "+1029384756",
        "Address": "321 Cedar Boulevard",
        "City": "Houston",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:25:00",
        "CompanyID": 1
    },
    {
        "ClientID": 5,
        "FirstName": "Emily",
        "LastName": "Davis",
        "Email": "emily.davis@example.com",
        "PhoneNumber": "+1122334455",
        "Address": "654 Spruce Lane",
        "City": "Phoenix",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:30:00",
        "CompanyID": 1
    },
    {
        "ClientID": 6,
        "FirstName": "Frank",
        "LastName": "Miller",
        "Email": "frank.miller@example.com",
        "PhoneNumber": "+1555444333",
        "Address": "987 Birch Street",
        "City": "Philadelphia",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:35:00",
        "CompanyID": 1
    },
    {
        "ClientID": 7,
        "FirstName": "Grace",
        "LastName": "Wilson",
        "Email": "grace.wilson@example.com",
        "PhoneNumber": "+1444555666",
        "Address": "222 Elm Avenue",
        "City": "San Antonio",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:40:00",
        "CompanyID": 1
    },
    {
        "ClientID": 8,
        "FirstName": "Henry",
        "LastName": "Moore",
        "Email": "henry.moore@example.com",
        "PhoneNumber": "+1777888999",
        "Address": "333 Ash Road",
        "City": "San Diego",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:45:00",
        "CompanyID": 1
    },
    {
        "ClientID": 9,
        "FirstName": "Ivy",
        "LastName": "Taylor",
        "Email": "ivy.taylor@example.com",
        "PhoneNumber": "+1222444666",
        "Address": "444 Willow Street",
        "City": "Dallas",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:50:00",
        "CompanyID": 1
    },
    {
        "ClientID": 10,
        "FirstName": "Jack",
        "LastName": "Anderson",
        "Email": "jack.anderson@example.com",
        "PhoneNumber": "+1999888777",
        "Address": "555 Maple Avenue",
        "City": "San Jose",
        "Country": "USA",
        "CreatedAt": "2024-08-21 14:55:00",
        "CompanyID": 1
    },
    {
        "ClientID": 11,
        "FirstName": "Karen",
        "LastName": "Thomas",
        "Email": "karen.thomas@example.com",
        "PhoneNumber": "+1333777888",
        "Address": "666 Pine Boulevard",
        "City": "Austin",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:00:00",
        "CompanyID": 1
    },
    {
        "ClientID": 12,
        "FirstName": "Leo",
        "LastName": "Jackson",
        "Email": "leo.jackson@example.com",
        "PhoneNumber": "+1222333444",
        "Address": "777 Cedar Lane",
        "City": "Jacksonville",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:05:00",
        "CompanyID": 1
    },
    {
        "ClientID": 13,
        "FirstName": "Mia",
        "LastName": "White",
        "Email": "mia.white@example.com",
        "PhoneNumber": "+1555222333",
        "Address": "888 Birch Avenue",
        "City": "San Francisco",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:10:00",
        "CompanyID": 1
    },
    {
        "ClientID": 14,
        "FirstName": "Nick",
        "LastName": "Harris",
        "Email": "nick.harris@example.com",
        "PhoneNumber": "+1444333222",
        "Address": "999 Elm Street",
        "City": "Indianapolis",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:15:00",
        "CompanyID": 1
    },
    {
        "ClientID": 15,
        "FirstName": "Olivia",
        "LastName": "Martin",
        "Email": "olivia.martin@example.com",
        "PhoneNumber": "+1111222233",
        "Address": "111 Spruce Road",
        "City": "Columbus",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:20:00",
        "CompanyID": 1
    },
    {
        "ClientID": 16,
        "FirstName": "Paul",
        "LastName": "Clark",
        "Email": "paul.clark@example.com",
        "PhoneNumber": "+1555666777",
        "Address": "222 Maple Boulevard",
        "City": "Fort Worth",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:25:00",
        "CompanyID": 2
    },
    {
        "ClientID": 17,
        "FirstName": "Quinn",
        "LastName": "Lewis",
        "Email": "quinn.lewis@example.com",
        "PhoneNumber": "+1999444333",
        "Address": "333 Oak Lane",
        "City": "Charlotte",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:30:00",
        "CompanyID": 2
    },
    {
        "ClientID": 18,
        "FirstName": "Rose",
        "LastName": "Walker",
        "Email": "rose.walker@example.com",
        "PhoneNumber": "+1333444555",
        "Address": "444 Pine Avenue",
        "City": "Detroit",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:35:00",
        "CompanyID": 2
    },
    {
        "ClientID": 19,
        "FirstName": "Sam",
        "LastName": "Young",
        "Email": "sam.young@example.com",
        "PhoneNumber": "+1222555777",
        "Address": "555 Cedar Street",
        "City": "El Paso",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:40:00",
        "CompanyID": 3
    },
    {
        "ClientID": 20,
        "FirstName": "Tina",
        "LastName": "King",
        "Email": "tina.king@example.com",
        "PhoneNumber": "+1555333444",
        "Address": "666 Birch Lane",
        "City": "Memphis",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:45:00",
        "CompanyID": 3
    },
    {
        "ClientID": 21,
        "FirstName": "Uma",
        "LastName": "Scott",
        "Email": "uma.scott@example.com",
        "PhoneNumber": "+1444666888",
        "Address": "777 Willow Road",
        "City": "Boston",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:50:00",
        "CompanyID": 3
    },
    {
        "ClientID": 22,
        "FirstName": "Victor",
        "LastName": "Green",
        "Email": "victor.green@example.com",
        "PhoneNumber": "+1777222444",
        "Address": "888 Elm Avenue",
        "City": "Seattle",
        "Country": "USA",
        "CreatedAt": "2024-08-21 15:55:00",
        "CompanyID": 3
    },
    {
        "ClientID": 23,
        "FirstName": "Wendy",
        "LastName": "Baker",
        "Email": "wendy.baker@example.com",
        "PhoneNumber": "+1999333222",
        "Address": "999 Maple Road",
        "City": "Denver",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:00:00",
        "CompanyID": 4
    },
    {
        "ClientID": 24,
        "FirstName": "Xander",
        "LastName": "Carter",
        "Email": "xander.carter@example.com",
        "PhoneNumber": "+1222333666",
        "Address": "111 Oak Street",
        "City": "Washington",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:05:00",
        "CompanyID": 4
    },
    {
        "ClientID": 25,
        "FirstName": "Yara",
        "LastName": "Mitchell",
        "Email": "yara.mitchell@example.com",
        "PhoneNumber": "+1333888777",
        "Address": "222 Pine Avenue",
        "City": "Nashville",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:10:00",
        "CompanyID": 4
    },
    {
        "ClientID": 26,
        "FirstName": "Zane",
        "LastName": "Reed",
        "Email": "zane.reed@example.com",
        "PhoneNumber": "+1555777888",
        "Address": "333 Cedar Lane",
        "City": "Baltimore",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:15:00",
        "CompanyID": 4
    },
    {
        "ClientID": 27,
        "FirstName": "Oscar",
        "LastName": "Wright",
        "Email": "oscar.wright@example.com",
        "PhoneNumber": "+1777666999",
        "Address": "444 Birch Avenue",
        "City": "Louisville",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:20:00",
        "CompanyID": 4
    },
    {
        "ClientID": 28,
        "FirstName": "Peter",
        "LastName": "Robinson",
        "Email": "peter.robinson@example.com",
        "PhoneNumber": "+1999222111",
        "Address": "555 Elm Road",
        "City": "Milwaukee",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:25:00",
        "CompanyID": 4
    },
    {
        "ClientID": 29,
        "FirstName": "Quincy",
        "LastName": "Parker",
        "Email": "quincy.parker@example.com",
        "PhoneNumber": "+1222999666",
        "Address": "666 Maple Street",
        "City": "Albuquerque",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:30:00",
        "CompanyID": 4
    },
    {
        "ClientID": 30,
        "FirstName": "Rachel",
        "LastName": "Adams",
        "Email": "rachel.adams@example.com",
        "PhoneNumber": "+1333444333",
        "Address": "777 Oak Boulevard",
        "City": "Tucson",
        "Country": "USA",
        "CreatedAt": "2024-08-21 16:35:00",
        "CompanyID": 4
    }
]
